# This workflow will build the source code and create a new github package.
# For more information see: https://github.com/marketplace/actions/build-and-push-docker-images

name: Build

on:
  push:
    branches:
      - master
      - develop
    tags:
      - v*
      - Sv*
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ${{ github.actor }}
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.GITHUB_TOKEN }}
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ghcr.io
        # Docker repository to tag the image with
        repository: talview/speedtest/speedtest
        # Automatically tags the built image with the git reference as per the readme
        tag_with_ref: true
        tag_with_sha: true
        # Path to the build context
        path: .
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        dockerfile: Dockerfile
        # Always attempt to pull a newer version of the image
        always_pull: true
        # Comma-delimited list of images to consider as cache sources
        cache_froms: talview/speedtest/speedtest:develop,talview/speedtest/speedtest:latest
        # Adds labels with git repository information to the built image
        add_git_labels: true
        # Whether to push the image
        push: true